name 'webserver'
version '2.1.0'
maintainer 'Acme Infra'
maintainer_email 'infra@acme.test'
license 'Apache-2.0'
description 'Installs and configures the acme web server'
source_url 'https://github.com/acme/webserver'
issues_url 'https://github.com/acme/webserver/issues'

depends 'apt', '>= 7.0'
depends 'build-essential'
