// gendocs regenerates the per-command Markdown reference under
// docs/commands/ from the live cobra command tree, plus a top-level
// README.md index that links to each per-command page with a one-line
// summary pulled from each command's Short.
//
// Usage: go run ./tools/gendocs [output-dir]
//
// The default output directory is docs/commands relative to the
// current working directory. The tool wipes the target directory
// before writing so deleted commands do not linger as stale files.
//
// To keep generated output reproducible the cobra "auto-generated"
// timestamp footer is suppressed.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"

	"github.com/tas50/cinc-cli/apps/cinc/cmd"
)

func main() {
	outDir := "docs/commands"
	if len(os.Args) > 1 {
		outDir = os.Args[1]
	}

	if err := os.RemoveAll(outDir); err != nil {
		exit("clear %s: %v", outDir, err)
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		exit("create %s: %v", outDir, err)
	}

	root := cmd.NewRootCmd()
	root.DisableAutoGenTag = true

	if err := doc.GenMarkdownTreeCustom(root, outDir, frontmatter, linkHandler); err != nil {
		exit("generate docs: %v", err)
	}

	if err := writeIndex(root, outDir); err != nil {
		exit("write index: %v", err)
	}

	abs, _ := filepath.Abs(outDir)
	fmt.Printf("Wrote %s\n", abs)
}

// frontmatter returns an empty prefix; we keep the generated output as
// plain Markdown without any static-site frontmatter.
func frontmatter(string) string { return "" }

// linkHandler rewrites the cross-references cobra emits in the "SEE
// ALSO" section so they resolve relative to docs/commands/ rather than
// pointing at the parent docs/ directory.
func linkHandler(name string) string {
	base := strings.TrimSuffix(name, ".md")
	return base + ".md"
}

// writeIndex builds docs/commands/README.md: a flat alphabetical list
// of every command in the tree, each line linking to that command's
// generated page and showing its cobra Short summary.
func writeIndex(root *cobra.Command, outDir string) error {
	type entry struct {
		path     string // e.g. "cinc client create"
		filename string // e.g. "cinc_client_create.md"
		short    string
	}
	var entries []entry
	var walk func(*cobra.Command)
	walk = func(c *cobra.Command) {
		if c.Hidden || !c.IsAvailableCommand() && c != root {
			return
		}
		entries = append(entries, entry{
			path:     c.CommandPath(),
			filename: strings.ReplaceAll(c.CommandPath(), " ", "_") + ".md",
			short:    c.Short,
		})
		for _, sub := range c.Commands() {
			walk(sub)
		}
	}
	walk(root)
	sort.Slice(entries, func(i, j int) bool { return entries[i].path < entries[j].path })

	var b strings.Builder
	fmt.Fprintln(&b, "# Command reference")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "Every command in the `cinc` tree, with a one-line summary and a")
	fmt.Fprintln(&b, "link to the full reference page. This file is regenerated by")
	fmt.Fprintln(&b, "`make docs` from the live cobra command tree — do not edit by hand.")
	fmt.Fprintln(&b)
	for _, e := range entries {
		fmt.Fprintf(&b, "- [`%s`](%s) — %s\n", e.path, e.filename, e.short)
	}

	return os.WriteFile(filepath.Join(outDir, "README.md"), []byte(b.String()), 0o644)
}

func exit(format string, a ...any) {
	fmt.Fprintf(os.Stderr, "gendocs: "+format+"\n", a...)
	os.Exit(1)
}
