//go:build acceptance

package acceptance

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/tas50/cinc-cli/cli/policyfile/rubyeval"
)

// requireRubyEngine downloads/caches the pinned ruby.wasm the same way the unit
// corpus does, skipping the whole test cleanly (with a clear message) when the
// blob can't be fetched — so a network-less CI still passes. When it succeeds
// the runtime is cached, so the cinc binary subprocess reuses it without a
// second download.
func requireRubyEngine(t *testing.T) {
	t.Helper()
	if err := rubyeval.NewEngine().Available(); err != nil {
		if rubyeval.IsUnavailable(err) {
			t.Skipf("skipping: embedded ruby.wasm runtime unavailable (network needed on first run): %v", err)
		}
		t.Fatalf("unexpected ruby.wasm availability error: %v", err)
	}
}

// writeInstallFixture lays down a Policyfile.rb that uses DYNAMIC Ruby (its
// run_list is built in a loop and a cookbook is added conditionally) plus a
// path-sourced cookbook on local disk, so the flow exercises the real embedded
// Ruby engine without needing Supermarket to be reachable. It returns the dir.
func writeInstallFixture(t *testing.T, policyName string) string {
	t.Helper()
	dir := t.TempDir()

	cb := filepath.Join(dir, "cookbooks", "installcb", "recipes")
	if err := os.MkdirAll(cb, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "cookbooks", "installcb", "metadata.rb"),
		[]byte("name 'installcb'\nversion '1.0.0'\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(cb, "default.rb"), []byte("log 'installed via policy install'\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	policyfile := "name '" + policyName + `'
default_source :supermarket

# Dynamic Ruby: the run_list is generated by a loop, proving the embedded CRuby
# engine evaluates arbitrary Ruby (not a static parser) against a live server.
%w[web app db].each do |tier|
  run_list "role[#{tier}]" if tier != 'db'
end
run_list(['recipe[installcb::default]'] + %w[web app].map { |t| "role[#{t}]" })

# Path-sourced cookbook on local disk (no Supermarket needed).
cookbook 'installcb', path: 'cookbooks/installcb'

# Conditional cookbook, off by default here.
cookbook 'extras' if ENV['CINC_ACCEPTANCE_EXTRAS'] == '1'

default['installcb']['port'] = 8080
`
	if err := os.WriteFile(filepath.Join(dir, "Policyfile.rb"), []byte(policyfile), 0o644); err != nil {
		t.Fatal(err)
	}
	return dir
}

// TestPolicyInstallEvaluatesDynamicPolicyfile runs the REAL compiled cinc
// binary's `policy install` against a fresh cinc-zero, evaluating a dynamic
// Policyfile.rb through the embedded ruby.wasm engine and asserting the written
// lock reflects the dynamically-generated run_list and the path cookbook.
//
// Evaluation is local (the engine does not call the server); cinc-zero is up so
// this is a faithful end-to-end run of the binary in a server-provisioned
// environment, and the companion push test below completes the real round-trip.
func TestPolicyInstallEvaluatesDynamicPolicyfile(t *testing.T) {
	requireRubyEngine(t)
	env, stop := startAcceptance(t)
	defer stop()

	dir := writeInstallFixture(t, "installtest")
	out := runCinc(t, env.binary, "policy", "install",
		filepath.Join(dir, "Policyfile.rb"), "--config", env.cfgPath)
	if !strings.Contains(out, "evaluation-only lock") {
		t.Errorf("expected the evaluation-vs-resolution note in output:\n%s", out)
	}

	lock := readInstallLock(t, filepath.Join(dir, "Policyfile.lock.json"))
	wantRunList := []any{"recipe[installcb::default]", "role[web]", "role[app]"}
	if got := lock["run_list"]; !jsonEqual(got, wantRunList) {
		t.Errorf("lock run_list = %v, want %v (built dynamically)", got, wantRunList)
	}
	cbs, _ := lock["cookbook_locks"].(map[string]any)
	if _, ok := cbs["installcb"]; !ok {
		t.Errorf("lock missing installcb cookbook: %v", cbs)
	}
	if _, ok := cbs["extras"]; ok {
		t.Errorf("extras cookbook should be absent (env unset): %v", cbs)
	}
}

// TestPolicyInstallThenPushRoundTrips proves the eval -> lock -> push pipeline
// end-to-end against a live cinc-zero: it evaluates a dynamic Policyfile with
// the engine, then pushes the resulting lock to a policy group and confirms the
// policy and its group assignment landed on the server.
//
// HONEST BOUNDARY: `cinc policy install` performs EVALUATION only — it does not
// solve cookbook versions or compute chef-identical cookbook identifiers (see
// cli/policyfile/rubyeval/doc.go). A push-ready lock needs those, so this test
// completes the engine-produced lock with a revision id and a placeholder
// cookbook identifier/version before pushing. That completion is the missing
// resolver step, stubbed here on purpose; everything else — the run_list,
// attributes, and path source — is exactly what the engine produced.
func TestPolicyInstallThenPushRoundTrips(t *testing.T) {
	requireRubyEngine(t)
	env, stop := startAcceptance(t)
	defer stop()

	dir := writeInstallFixture(t, "installpush")
	runCinc(t, env.binary, "policy", "install",
		filepath.Join(dir, "Policyfile.rb"), "--config", env.cfgPath)

	lockPath := filepath.Join(dir, "Policyfile.lock.json")
	lock := readInstallLock(t, lockPath)

	// --- resolver stub: fill the fields install intentionally leaves blank ---
	const identifier = "0123456789abcdef0123456789abcdef01234567"
	lock["revision_id"] = identifier
	cbs := lock["cookbook_locks"].(map[string]any)
	installcb := cbs["installcb"].(map[string]any)
	installcb["version"] = "1.0.0"
	installcb["identifier"] = identifier
	installcb["dotted_decimal_identifier"] = "1.2.3"
	// ------------------------------------------------------------------------

	data, _ := json.MarshalIndent(lock, "", "  ")
	if err := os.WriteFile(lockPath, data, 0o644); err != nil {
		t.Fatal(err)
	}

	push := runCinc(t, env.binary, "policy", "push", "qa", lockPath, "--config", env.cfgPath)
	if !strings.Contains(push, `Pushed policy "installpush"`) || !strings.Contains(push, `group "qa"`) {
		t.Fatalf("policy push output = %q", push)
	}

	list := runCinc(t, env.binary, "policy", "list", "--config", env.cfgPath)
	if !strings.Contains(list, "installpush") {
		t.Errorf("policy list after push missing installpush:\n%s", list)
	}

	group := runCinc(t, env.binary, "policy-group", "show", "qa", "--config", env.cfgPath, "--format", "json")
	if !strings.Contains(group, "installpush") {
		t.Errorf("policy-group show qa missing installpush:\n%s", group)
	}

	// `policy show` returns the revision index; confirm our pushed revision id
	// is present (the run_list content itself is asserted against the lock in
	// TestPolicyInstallEvaluatesDynamicPolicyfile).
	show := runCinc(t, env.binary, "policy", "show", "installpush", "--config", env.cfgPath, "--format", "json")
	if !strings.Contains(show, identifier) {
		t.Errorf("policy show missing the pushed revision %s:\n%s", identifier, show)
	}
}

func readInstallLock(t *testing.T, path string) map[string]any {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read lock: %v", err)
	}
	var m map[string]any
	if err := json.Unmarshal(data, &m); err != nil {
		t.Fatalf("lock not valid JSON: %v", err)
	}
	return m
}

func jsonEqual(got any, want []any) bool {
	arr, ok := got.([]any)
	if !ok || len(arr) != len(want) {
		return false
	}
	for i := range want {
		if arr[i] != want[i] {
			return false
		}
	}
	return true
}
