//go:build acceptance

package acceptance

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/tas50/cinc-cli/cli/policyfile/rubyeval"
)

// requireRubyEngine downloads/caches the pinned ruby.wasm the same way the unit
// corpus does, skipping the whole test cleanly (with a clear message) when the
// blob can't be fetched — so a network-less CI still passes. When it succeeds
// the runtime is cached, so the cinc binary subprocess reuses it without a
// second download.
func requireRubyEngine(t *testing.T) {
	t.Helper()
	if err := rubyeval.NewEngine().Available(); err != nil {
		if rubyeval.IsUnavailable(err) {
			t.Skipf("skipping: embedded ruby.wasm runtime unavailable (network needed on first run): %v", err)
		}
		t.Fatalf("unexpected ruby.wasm availability error: %v", err)
	}
}

// writeInstallFixture lays down a Policyfile.rb that uses DYNAMIC Ruby (its
// run_list is built in a loop and a cookbook is added conditionally) plus two
// path-sourced cookbooks with a transitive dependency between them, so the flow
// exercises the embedded Ruby engine AND the dependency resolver end to end
// without needing Supermarket to be reachable. It returns the dir.
func writeInstallFixture(t *testing.T, policyName string) string {
	t.Helper()
	dir := t.TempDir()

	writeInstallCookbook(t, dir, "installcb", "1.0.0", "'installdep', '~> 2.0'")
	writeInstallCookbook(t, dir, "installdep", "2.3.0")

	policyfile := "name '" + policyName + `'

# Dynamic Ruby: the run_list is generated by a loop, proving the embedded CRuby
# engine evaluates arbitrary Ruby (not a static parser).
run_list(%w[installcb].map { |c| "#{c}::default" })

# Path-sourced cookbooks on local disk (no Supermarket needed). installcb
# depends on installdep, which the resolver must pull into the solution.
cookbook 'installcb', path: 'cookbooks/installcb'
cookbook 'installdep', path: 'cookbooks/installdep'

# Conditional cookbook, off by default here.
cookbook 'extras', path: 'cookbooks/extras' if ENV['CINC_ACCEPTANCE_EXTRAS'] == '1'

default['installcb']['port'] = 8080
`
	if err := os.WriteFile(filepath.Join(dir, "Policyfile.rb"), []byte(policyfile), 0o644); err != nil {
		t.Fatal(err)
	}
	return dir
}

// writeInstallCookbook scaffolds a path cookbook with metadata.rb and a
// default recipe under dir/cookbooks/<name>.
func writeInstallCookbook(t *testing.T, dir, name, version string, depends ...string) {
	t.Helper()
	cbDir := filepath.Join(dir, "cookbooks", name)
	if err := os.MkdirAll(filepath.Join(cbDir, "recipes"), 0o755); err != nil {
		t.Fatal(err)
	}
	md := "name '" + name + "'\nversion '" + version + "'\n"
	for _, d := range depends {
		md += "depends " + d + "\n"
	}
	if err := os.WriteFile(filepath.Join(cbDir, "metadata.rb"), []byte(md), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(cbDir, "recipes", "default.rb"), []byte("log '"+name+"'\n"), 0o644); err != nil {
		t.Fatal(err)
	}
}

// TestPolicyInstallResolvesPushReadyLock runs the REAL compiled cinc binary's
// `policy install` against a fresh cinc-zero, resolving a dynamic Policyfile.rb
// (embedded ruby.wasm) into a fully-resolved lock and asserting it is
// push-ready: every cookbook lock carries a content identifier and a
// dotted-decimal identifier, plus a revision_id and solution_dependencies.
//
// Resolution is local (the engine and solver do not call the server); cinc-zero
// is up so this is a faithful end-to-end run of the binary, and the companion
// push test below completes the real round-trip.
func TestPolicyInstallResolvesPushReadyLock(t *testing.T) {
	requireRubyEngine(t)
	env, stop := startAcceptance(t)
	defer stop()

	dir := writeInstallFixture(t, "installtest")
	out := runCinc(t, env.binary, "policy", "install",
		filepath.Join(dir, "Policyfile.rb"), "--config", env.cfgPath)
	if !strings.Contains(out, "revision id:") {
		t.Errorf("expected a resolved summary with a revision id:\n%s", out)
	}

	lock := readInstallLock(t, filepath.Join(dir, "Policyfile.lock.json"))
	wantRunList := []any{"recipe[installcb::default]"}
	if got := lock["run_list"]; !jsonEqual(got, wantRunList) {
		t.Errorf("lock run_list = %v, want %v", got, wantRunList)
	}
	if lock["revision_id"] == "" || lock["revision_id"] == nil {
		t.Error("lock missing revision_id (not push-ready)")
	}
	if _, ok := lock["solution_dependencies"].(map[string]any); !ok {
		t.Error("lock missing solution_dependencies")
	}
	cbs, _ := lock["cookbook_locks"].(map[string]any)
	// installcb's dependency installdep must be pulled into the solution.
	for _, want := range []string{"installcb", "installdep"} {
		entry, ok := cbs[want].(map[string]any)
		if !ok {
			t.Errorf("lock missing cookbook %q: %v", want, cbs)
			continue
		}
		if s, _ := entry["identifier"].(string); len(s) != 40 {
			t.Errorf("cookbook %q identifier = %q, want a 40-char SHA1", want, entry["identifier"])
		}
		if entry["dotted_decimal_identifier"] == "" || entry["dotted_decimal_identifier"] == nil {
			t.Errorf("cookbook %q missing dotted_decimal_identifier", want)
		}
	}
	if _, ok := cbs["extras"]; ok {
		t.Errorf("extras cookbook should be absent (env unset): %v", cbs)
	}
}

// TestPolicyInstallThenPushRoundTrips proves the full install -> resolve ->
// push pipeline end-to-end against a live cinc-zero: `policy install` resolves
// the Policyfile into a real, push-ready lock (no stubbing), then `policy push`
// uploads every cookbook artifact under its computed identifier and associates
// the revision with a policy group. We then confirm via the server that the
// revision landed and that each cookbook artifact exists under the exact
// identifier the resolver computed.
func TestPolicyInstallThenPushRoundTrips(t *testing.T) {
	requireRubyEngine(t)
	env, stop := startAcceptance(t)
	defer stop()

	dir := writeInstallFixture(t, "installpush")
	runCinc(t, env.binary, "policy", "install",
		filepath.Join(dir, "Policyfile.rb"), "--config", env.cfgPath)

	lockPath := filepath.Join(dir, "Policyfile.lock.json")
	lock := readInstallLock(t, lockPath)
	revisionID, _ := lock["revision_id"].(string)
	if revisionID == "" {
		t.Fatal("resolved lock has no revision_id")
	}
	cbs := lock["cookbook_locks"].(map[string]any)
	wantIDs := map[string]string{}
	for _, name := range []string{"installcb", "installdep"} {
		id, _ := cbs[name].(map[string]any)["identifier"].(string)
		wantIDs[name] = id
	}

	push := runCinc(t, env.binary, "policy", "push", "qa", lockPath, "--config", env.cfgPath)
	if !strings.Contains(push, `Pushed policy "installpush"`) || !strings.Contains(push, `group "qa"`) {
		t.Fatalf("policy push output = %q", push)
	}

	list := runCinc(t, env.binary, "policy", "list", "--config", env.cfgPath)
	if !strings.Contains(list, "installpush") {
		t.Errorf("policy list after push missing installpush:\n%s", list)
	}

	group := runCinc(t, env.binary, "policy-group", "show", "qa", "--config", env.cfgPath, "--format", "json")
	if !strings.Contains(group, "installpush") {
		t.Errorf("policy-group show qa missing installpush:\n%s", group)
	}

	// `policy show` returns the revision index keyed by revision id; confirm the
	// revision id the resolver computed is what landed on the server.
	show := runCinc(t, env.binary, "policy", "show", "installpush", "--config", env.cfgPath, "--format", "json")
	if !strings.Contains(show, revisionID) {
		t.Errorf("policy show missing the resolved revision %s:\n%s", revisionID, show)
	}

	// Each cookbook artifact must exist on the server under the identifier the
	// resolver computed, proving the computed identifiers are server-valid.
	c := acceptanceClient(t, env)
	for name, id := range wantIDs {
		entry, _, err := c.CookbookArtifacts.GetVersions(context.Background(), name)
		if err != nil {
			t.Errorf("cookbook artifact %q not found on server: %v", name, err)
			continue
		}
		found := false
		for _, v := range entry.Versions {
			if v.Identifier == id {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("cookbook artifact %q is missing computed identifier %s; have %+v", name, id, entry.Versions)
		}
	}
}

func readInstallLock(t *testing.T, path string) map[string]any {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read lock: %v", err)
	}
	var m map[string]any
	if err := json.Unmarshal(data, &m); err != nil {
		t.Fatalf("lock not valid JSON: %v", err)
	}
	return m
}

func jsonEqual(got any, want []any) bool {
	arr, ok := got.([]any)
	if !ok || len(arr) != len(want) {
		return false
	}
	for i := range want {
		if arr[i] != want[i] {
			return false
		}
	}
	return true
}
